config/routes.rb
Showboarder::Application.routes.draw do
  devise_for :users, :path => '/users', :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'static_pages#home'

  # devise_scope :user do
  #   match '/auth/stripe_connect/callback' => 'users/omniauth_callbacks#stripe_connect', :as => :auth_callback, via: [:get, :post]
  # end
  # devise_scope :user do
  #   get '/auth/stripe_connect/callback', to: 'users/omniauth_callbacks#stripe_connect'
  # end

  match '/about',   to: 'static_pages#about',   via: 'get'
  
  match '/status/:guid'      => 'sales#status',   via: :get,  as: :status
  match '/confirm/:guid'     => 'sales#show',     via: :get,  as: :confirm
  match '/esuggest/:act', to: 'acts#esuggest', via: 'get'
  match '/eretrieve/', to: 'acts#eretrieve', via: 'get'
  match '/ticketrelease/:ticket', to: 'tickets#release', via: :post
  match '/clearcart', to: 'tickets#clear', via: :post

  resources :users, only: [:show] do
    match '/stripe-connect' => 'users#stripe_connect', via: :get
  end

  resources :boards, only: [:create]

  resources :boards, except: [:index, :create], path:'' do
    match '/ticketed'    => 'boards#ticketed',      via: :get
    resources :shows do
      match '/checkin', to: 'shows#checkin', via: :get
      match '/checkinattendee', to: 'shows#checkin_attendee', via: :post
      match '/checkoutattendee', to: 'shows#checkout_attendee', via: :post
      match '/attendees', to: 'shows#attendees', via: :get
      match '/checkout', to: 'shows#checkout', via: :get
      match '/checkout', to: 'sales#checkout', via: :post
      match '/reserve', to: 'tickets#reserve', via: :post
    end
    resources :stages, only: [:create]
  end

  resources :acts, only: [:show]
  
  resources :stripe_events, only: [:create]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @user = current_user
      if @user.boards.count == 1
        @board = @user.boards.first
        @shows = @board.shows.where("show_at > ?", Date.tomorrow).order(:show_at).paginate(page: params[:page])
      end
      @tickets_by_show = @user.tickets_by_show

      render layout: "application"
    else
      render layout: "landing"
    end
  end
end

private

  def guest_params
    params.fetch(:guest, {})
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  class ActionView::Helpers::FormBuilder
    def inputbox_field(method, options = {})
      text_field(method, options.merge(class: 'form-control'))
    end
  end
end

app/views/static_pages/_signed_in_no_board.html.erb
<section>
  <div class="row">
    <div class="col-xs-12 text-center">
      <h1>Your Tickets</h1>
      <% if @tickets_by_show.count > 0 %>
        <% @tickets_by_show.each do |h, k| %>
          <%= k.count %> tickets to <%= link_to h.board.name, h.board %> on <%= link_to h.show_at.to_time.strftime('%b %e'), board_show_path(h.board, h), :class => "band-link" %>
        <% end %>
      <% else %>
        <p>Any tickets you purchase will appear here.  You currently have no purchased tickets.</p>
      <% end %>
      <br>
      <br>
      <br>
      <hr>
      <p style="margin:0px 0px 0;">
        Have a venue?
      </p>
      <%= link_to "Create a Showboard Now", new_board_path, class: "btn btn-primary" %>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
 <% if user_signed_in? %>
  <% if @board %>
    <%= render :file => 'boards/show' %>
  <% else %>
    <%= render 'static_pages/signed_in_no_board' %>
  <% end %>
<% else %>
  <header id="home">
  
    <div class="container text-center">

      <h1 class="big-text">Showboarder</h1>

      <p class="header-slug">The simplest way for cash-at-the-door venues to list shows and sell tickets online</p>


      <div class="row landing-buttons">
        <div class="col-sm-4 col-sm-offset-2 col-xs-6 col-xs-offset-3">

          <%= link_to "Create a Showboard", new_board_path, class: "btn btn-color2 btn-block btn-header1" %>
        </div>
        <div class="col-sm-4 col-sm-offset-0 col-xs-6 col-xs-offset-3"><a href="#services" class="scrollto">
          <button name="submit" type="submit" class="btn btn-color1 btn-block btn-header2" data-error-message="Error!" data-sending-message="Sending..." data-ok-message="Message Sent">Learn more</button></a>
        </div>
      </div>
    
    </div>
    
  </header><!--End header -->


    <!-- ==============================================
    SERVICES2
    =============================================== -->
    <section id="services" class="add-padding-tiny bg-color3">
    
      <div class="container">
        
        <h1 class="section-title scrollimation fade-up large-text">A Showboard is a list of your venue's upcoming shows</h1>

        <div class="row">

          <div class="col-xs-12 text-center scrollimation fade-up">
          
            <%= image_tag('devices-preview.png', :height=>320, class: "devices-preview") %>  
            
            <h3>Just post a show and online ticketing is taken care of automatically</h3>

          </div>

        </div>

        <div class="row">
          <div class="col-sm-12 text-center">
            <a href="#services2" class="scrollto btn btn-circle-2 tight"><i class="fa fa-angle-double-down"></i></a>
          </div>
          
        </div>
      </div>
    
    </section>  

    <!-- ==============================================
    SERVICES2
    =============================================== -->
    <section id="services2" class="add-padding-tiny">
    
      <div class="container">
        
        <h1 class="section-title scrollimation fade-up large-text">OFFERING THE OPTION TO BUY TICKETS ONLINE IS...</h1>

        <div class="row">

          <div class="col-sm-4 service-item color2 scrollimation scale-in">
          
            <div class="service-icon"><i class="fa fa-dollar"></i></div>
            
            <h2><strong>Better for Business</strong></h2>
            
            <p>Showboarder gives your venue a home online that is free to use, mobile friendly, and dead simple to manage. Posting shows is easy and ticketing is automatic.</p>
            
          </div>

          <div class="col-sm-4 service-item color1 scrollimation scale-in d1">
          
            <div class="service-icon"><i class="fa fa-music"></i></div>
            
            <h2><strong>Better for Performers</strong></h2>
            
            <p class="margin-top">Showboarder event pages make shows easier to promote, and letting fans buy tickets online helps ensure they make it out to the show.</p>
            
            
          </div>

          <div class="col-sm-4 service-item color3 scrollimation scale-in d2">
          
            <div class="service-icon"><i class="fa fa-heart"></i></div>
            
            <h2><strong>Better for Fans</strong></h2>
            
            <p style="padding-bottom">No more getting slapped with huge ticket fees at checkout</p>
            
            <p class="margin-top">Instead of fees, fans can customize a voluntary tip for Showboarder or for charity. It finally makes sense to buy tickets online to local shows!</p>
            
            
          </div>
          
        </div>

        <div class="row">
          <div class="col-sm-12 text-center">
            <a href="#about" class="scrollto btn btn-circle tight"><i class="fa fa-angle-double-down"></i></a>
          </div>
          
        </div>
      </div>
    
    </section>  

    <!-- ==============================================
    ABOUT
    =============================================== -->
    <section id="about" class="add-padding-small bg-color2">
    
      <div class="container">
        
        <div class="row">
        
          <div class="col-sm-6 scrollimation fade-right d1">
          
            <img class="img-responsive polaroid" src=<%= asset_path "graphista/tip-pic2.jpg" %> alt="" />
          
          </div>
          
          <div class="col-sm-6 scrollimation fade-right d3">
          
            <h1 class="big-text">Customer Control</h1>

            <p class="lead">You keep 100% of the take from tickets, with the exception of the fees taken by <a href="https://stripe.com/us/pricing" target="_blank">our payment processor Stripe</a>.
            
            <p class="lead">Showboarder takes no cut, but instead lets consumers leave a voluntary tip for Showboarder or for <a href="http://www.littlekidsrock.org/" target="_blank">charity</a>.</p>

            
          
          </div>
        
        </div>

        <div class="row">
          <div class="col-sm-12 text-center">
            <a href="#analytics" class="scrollto btn btn-circle-2 tight media-tight"><i class="fa fa-angle-double-down"></i></a>
          </div>
          
        </div>        
        
      </div>
    
    </section>
  
    <!-- ==============================================
    SKILLS
    =============================================== -->
    <section id="analytics" class="add-padding-small border-bottom-color2">
    
      <div class="container">
        
        <div class="row">
        
          <div class="col-sm-6 col-md-5 text-right scrollimation fade-up d1">
          
            <h1 class="big-text">Detailed<br/>Analytics</h1>
            
            <p class="lead">Knowledge is power. Learn what works for your customers and your business.</p>
          
            <p>Traditional cash-at-the-door ticketing yields little information, but a little data can go a long way. Showboarder helps you learn who your customers are and how, when, and why they are buying.</p>
          
          </div>
        
          <div class="col-sm-6 col-md-5 col-md-offset-1">
          
            <div class="skills-bars">
            
              <div class="skills-item skill1">
                <span class="percent" data-percent="35">35%</span>
                <p>Repeat</p>
              </div>
              <div class="skills-item skill2">
                <span class="percent" data-percent="65">65%</span>
                <p>New Cust</p>
              </div>
              <div class="skills-item skill3">
                <span class="percent" data-percent="20">20%</span>
                <p>Door $</p>
              </div>
              <div class="skills-item skill4">
                <span class="percent" data-percent="80">80%</span>
                <p>Online $</p>
              </div>
              
            </div>
          
          </div>
          
        </div>
        
      
        <div class="row btn-end">
          <div class="col-sm-8 col-sm-offset-2 text-center">

            <%= link_to "Create a Showboard Now", new_board_path, class: "btn btn-color2 btn-create-board" %>
          </div>
        </div>
      </div>
    
    </section>

    <!-- ==============================================
    FOOTER
    =============================================== --> 
    
    <footer id="main-footer" class="add-padding bg-color3 border-top-color2">
    
      <div class="container">
      
        <ul class="social-links text-center">
          <li><a href="https://twitter.com/showboarder" target="_blank"><i class="fa fa-twitter fa-fw"></i></a></li>
          <li><a href="https://www.facebook.com/showboarder" target="_blank"><i class="fa fa-facebook fa-fw"></i></a></li>
          <li><a href="mailto:contact@showboarder.com" target="_blank"><i class="fa fa-envelope fa-fw"></i></a></li>
        </ul>
      
        
      </div>
      
    </footer>
    
    <!-- ==============================================
    SCRIPTS
    =============================================== --> 

    <script>//window.jQuery || document.write('<script src="assets/js/libs/jquery-1.8.2.js">\x3C/script>')</script>
    
    <%= javascript_include_tag "graphista/jquery.scrollto.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "graphista/waypoints.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "graphista/jquery.backstretch.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "graphista/scripts.js", "data-turbolinks-track" => true %>
    
    
  </body>
  
</html>
<% end %>