config/routes.rb
Showboarder::Application.routes.draw do
  devise_for :users, :path => '/users', :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'static_pages#home'

  # devise_scope :user do
  #   match '/auth/stripe_connect/callback' => 'users/omniauth_callbacks#stripe_connect', :as => :auth_callback, via: [:get, :post]
  # end
  # devise_scope :user do
  #   get '/auth/stripe_connect/callback', to: 'users/omniauth_callbacks#stripe_connect'
  # end

  match '/about',   to: 'static_pages#about',   via: 'get'
  
  match '/status/:guid'      => 'sales#status',   via: :get,  as: :status
  match '/confirm/:guid'     => 'sales#show',     via: :get,  as: :confirm
  match '/esuggest/:act', to: 'acts#esuggest', via: 'get'
  match '/eretrieve/', to: 'acts#eretrieve', via: 'get'
  match '/ticketrelease/:ticket', to: 'tickets#release', via: :post
  match '/clearcart', to: 'tickets#clear', via: :post

  resources :users, only: [:show] do
    match '/stripe-connect' => 'users#stripe_connect', via: :get
  end

  resources :boards, only: [:create]

  resources :boards, except: [:index, :create], path:'' do
    match '/ticketed'    => 'boards#ticketed',      via: :get
    resources :shows do
      match '/checkin', to: 'shows#checkin', via: :get
      match '/checkinattendee', to: 'shows#checkin_attendee', via: :post
      match '/checkoutattendee', to: 'shows#checkout_attendee', via: :post
      match '/attendees', to: 'shows#attendees', via: :get
      match '/checkout', to: 'shows#checkout', via: :get
      match '/checkout', to: 'sales#checkout', via: :post
      match '/reserve', to: 'tickets#reserve', via: :post
    end
    resources :stages, only: [:create]
  end

  resources :acts, only: [:show]
  
  resources :stripe_events, only: [:create]
end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :user_boards, foreign_key: "board_id", dependent: :destroy
  has_many :boarders, through: :user_boards, source: :boarder
  has_many :stages, dependent: :destroy
  has_many :shows, dependent: :destroy
  has_many :ext_links, as: :linkable, dependent: :destroy
  validates :vanity_url, presence: true, length: {minimum:4, maximum:20}
  validates :name, presence: true, length: {minimum:3, maximum:35}
  before_save { self.vanity_url = vanity_url.downcase }
  validates_format_of :vanity_url, :with => /[-a-z0-9_.]/
  accepts_nested_attributes_for :stages, :allow_destroy => true
  accepts_nested_attributes_for :shows, :allow_destroy => true
  accepts_nested_attributes_for :ext_links, :reject_if => :all_blank, :allow_destroy => true
  has_many :sales, as: :actionee
  has_attached_file :header_image, :s3_protocol => :https
  validates_attachment :header_image, :content_type => { :content_type => ["image/jpeg", "image/png"] }
  validates_with AttachmentSizeValidator, :attributes => :header_image, :less_than => 1.megabytes
  before_post_process :check_file_size
  has_many :email_subscriptions, :dependent => :destroy
  has_many :email_subscribers, :through => :email_subscriptions, :source => :email_subscriber, :source_type => "User"
  has_many :email_subscribers, :through => :email_subscriptions, :source => :email_subscriber, :source_type => "Guest"

  def check_file_size
    valid?
    errors[:image_file_size].blank?
  end

  def to_param
    vanity_url
  end

  def twitter_or_name
    if self.ext_links.where(ext_site: "Twitter") && self.ext_links.where(ext_site: "Twitter").count > 0
      twitter = "@" + self.ext_links.where(ext_site: "Twitter").first.url.split("/").last
      return twitter
    else
      return name
    end
  end

  def owner
    User.find_by_id(user_boards.find_by(board_id:self.id, role:"owner").boarder_id)
  end

  def boarder?(user)
    user_boards.find_by(boarder_id: user.id)
  end

  def board_role(user)
    user_boards.find_by(boarder_id: user.id).role
  end

  def paid?
    # user_boards.where(board_id:self.id, role:"owner").length > 0
    if self.paid_tier != 0
      return true
    else
      return false
    end
  end

  def stripe_connected?
    if self.boarders.first.stripe_recipient_id
      true
    else
      false
    end
  end

  def ext_links_fontawesomed
    links_html = ""
    self.ext_links.each do |e|
      if e.url && e.ext_site
        if e.ext_site == "Twitter"
          links_html = links_html + "<a href=\"#{e.url}\" target=\"_blank\"><i class=\"fa fa-twitter board-ext-link\"></i></a>"
        elsif e.ext_site == "Facebook"
          links_html = links_html + "<a href=\"#{e.url}\" target=\"_blank\"><i class=\"fa fa-facebook-square board-ext-link\"></i></a>"
        elsif e.ext_site == "Instagram"
          links_html = links_html + "<a href=\"#{e.url}\" target=\"_blank\"><i class=\"fa fa-instagram board-ext-link\"></i></a>"
        elsif e.ext_site == "Homepage"
          links_html = links_html + "<a href=\"#{e.url}\" target=\"_blank\"><i class=\"fa fa-home board-ext-link\"></i></a>"
        elsif e.ext_site == "Youtube"
          links_html = links_html + "<a href=\"#{e.url}\" target=\"_blank\"><i class=\"fa fa-youtube-play board-ext-link\"></i></a>"
        end
        if e != self.ext_links.last
          links_html = links_html + " "
        end
      end
    end
    if self.email && self.email != "" && self.email != " "
      links_html += "<a href=\"mailto:#{self.email}\" target=\"_blank\"><i class=\"fa fa-envelope board-ext-link\"></i></a>"
    end
    return links_html.html_safe
  end

  def self_zone
    place = self.stages.first.place
    result = GoogleTimezone.fetch(place.lat, place.lng, language: 'en', signature: ENV["GOOGLE_KEY"])
    self.update(timezone: result.time_zone_id)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  load_and_authorize_resource :board, :find_by => :vanity_url, :except => [:new]

  def new
    if !user_signed_in?
      redirect_to new_user_registration_path(:path_from => "create_board")
    else
      @board = Board.new
      @stage = @board.stages.build
    end
  end

  def edit
    @board = Board.find_by_vanity_url(params[:id])
    @stage = @board.stages.first
  end

  def update
    @board = Board.find_by_vanity_url(params[:id])
    @stage = @board.stages.first

    if @board.update(board_params) # TODO - allow for editing of google place
      flash[:success] = "Board updated"
      redirect_to @board
    else
      render 'edit'
    end
  end

  def ticketed
    #TODO Find out if/why this is getting called twice 
    @board = Board.find_by_vanity_url(params[:board_id])

    if user_signed_in? and !current_user.stripe_recipient_id
      redirect_to user_stripe_connect_path(current_user) and return
    elsif user_signed_in? and current_user.boarder?(@board) and (current_user.board_role(@board) == "manager") and current_user.stripe_recipient_id 
      current_user.board_role_assign(@board, "owner")
      @board.update(paid_tier: 1)

      flash[:success] = "Ticketing is now enabled for this showboard!" # TODO find out why this isn't showing
    else
      # TODO: re-implement this once double calling is fixed.
      # flash[:error] = "Sorry, you do not have significant permissions to complete this action."
    end
    redirect_to board_path(@board)
  end

  def create
    @board = Board.new(board_params)
    puts board_params
    if @board.save
      AdminMailer.delay.new_board(@board.id)
      puts @board.ext_links.count
      @board.stages.each do |s|
        s.places_gather
      end
      @board.self_zone
      @board.update_attributes(state:"public")
      current_user.boarder!(@board, "manager")
      flash[:success] = "You have created a new Showboard!"
      redirect_to @board
    else
      render 'boards/new'
    end
  end

  def show
    @board = Board.find_by_vanity_url(params[:id])

    @shows = @board.shows.where("show_at > ?", Date.tomorrow).order(:show_at).paginate(page: params[:page])
  end

  def destroy
    @board = Board.find_by_vanity_url(params[:id])
    @board.destroy
    flash[:success] = "You have deleted #{@board.name}!"
    redirect_to root_path
  end

  private

    def board_params
      params.require(:board).permit(:id, :name, :vanity_url, :header_image, :places_reference, :email, :paid_tier, :state, :ext_links_attributes => [:id, :board_id, :ext_site, :url, :linkable_type, :_destroy], :stages_attributes => [:id, :board_id, :name, :places_reference, :capacity, :places_json, :_destroy, :places_formatted_address_short])
    end
end

app/views/boards/_board.html.erb
<li>
  <%= link_to "#{board.name}", board, class: "btn btn-default btn-lg btn-front" %>
  <% if current_user.board_role(board) == "owner" || current_user.board_role(board) == "manager" %>
    <%= link_to "delete", board, method: :delete, id: board.id,
                                     data: { confirm: "You sure?" },
                                     title: board.name %>
    <% if board.paid_tier == 0 %>
      <%= link_to "Enable ticketing", board_ticketed_path(board) %>
    <% end %>
  <% end %>
  <br>
  <%= board.attributes %>
</li>

app/views/boards/_enable_ticketing_button.html.erb
<% if @board.paid_tier == 0 %>
  <%= link_to "Enable ticketing for this Showboard", board_ticketed_path(@board) %>
<% end %>

app/views/boards/edit.html.erb
<%= javascript_include_tag :eFormFocus %>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<section>
  <div class="container eternity-form">
    <div class="new-board-section">
      <div class="login-content text-center">
        <div class="section-title">
          <h3>Edit <%= link_to @board.name, @board %> Showboard</h3>
        </div>
        <%= simple_nested_form_for @board do |f| %>
          <div class="clearfix">
            <div class="textbox-wrap">
              <div class="input-group">
                <span class="input-group-addon "><i class="fa fa-user fa-color"></i></span>
                <%= f.text_field :name, :autofocus => true, class: "form-control", :placeholder => "Board Name" %>
              </div>
            </div>

            <div class="textbox-wrap">
              <div class="input-group">
                <span class="input-group-addon tight"><i class="fa fa-link fa-vanity"></i>showboarder.com/</span>
                <%= f.text_field :vanity_url, class: "form-control", style: "padding-left:2px;", :placeholder => "Custom Url" %>
              </div>
            </div>

            <div class="textbox-wrap">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope fa-color"></i></span>
                <%= f.email_field :email, class: "form-control", :placeholder => "My Venue's Contact email (optional)" %>
              </div>
            </div>

            <div class="textbox-wrap">
              <%= f.label :header_image, "Header Image (1800x700 .jpg or .png)" %>
              <%= f.file_field :header_image %>
            </div>
            <br>

            <%= f.fields_for :ext_links do |ext| %>
              <%= ext.select :ext_site, options_for_select(%w[Twitter Facebook Youtube Instagram], ext.object.ext_site), {}, {:class => "form-control ext-link-select"} %>
              <%= ext.input :url, input_html: {:class => "ext-link-url"}, input_html: {:style => "display:inline;max-width:300px;", :placeholder => "URL"}, label: false %>
              <%= ext.link_to_remove "<i class=\"fa fa-minus-circle\"></i>".html_safe, class: "btn-ext-link-remove" %>
            <% end %>  

          <div class="form-group">
            <%= f.link_to_add "<i class=\"fa fa-plus\"></i>Add a link (Facebook, Twitter, etc.)".html_safe, :ext_links, :class => "btn btn-success" %>
          </div>

          <%= f.fields_for :stages, @board.stages.first do |ff| %>

            <div class="textbox-wrap">
                
                <%= ff.input :capacity, input_html: {class:"form-control bfh-number", data_min: "0", value: @board.stages.first.capacity}, label: "Capacity (number of tickets available for each show)" %>
              </div> 
            
          <% end %>

          <%= f.button :submit, :class => "btn btn-primary btn-create-board" %>

          <p class="text-center"><%= link_to "Delete Board", @board, method: :delete, id: @board.id,
                                         data: { confirm: "Are you sure you would like to delete this board?  This cannot be undone." },
                                         title: @board.vanity_url, class: "btn btn-large btn-danger" %></p>

        <% end %>
      </div>
    </div>
  </div>
</div>
</section>

app/views/boards/new.html.erb
<%= javascript_include_tag :boardForm %>
<%= javascript_include_tag :eFormFocus %>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
<section>
  <div class="container eternity-form">
    <div class="new-board-section">
      <div class="login-content text-center">
        <div class="section-title">
          <h3>Create a new Showboard</h3>
        </div>
        <%= simple_nested_form_for @board, html:{id:"board-form"} do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div id="form-errors" class="alert alert-warning" style="display:none;">
          </div>

          <div class="clearfix">
            <div class="textbox-wrap">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa-color"></i></span>
                <%= f.text_field :name, :autofocus => true, class: "form-control", :placeholder => "My Venue's Name" %>
              </div>
            </div>

            <div class="textbox-wrap">
              <div class="input-group">
                <span class="input-group-addon tight"><i class="fa fa-link fa-vanity"></i>showboarder.com/</span>
                <%= f.text_field :vanity_url, class: "form-control", style: "padding-left:2px;", :placeholder => "Custom Showboard URL" %>
              </div>
            </div>

            <div class="textbox-wrap">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-envelope fa-color"></i></span>
                <%= f.email_field :email, class: "form-control", :placeholder => "My Venue's Contact email (optional)" %>
              </div>
            </div>

            <label>
              Your venue's links elsewhere online (Twitter, Facebook, etc.)
            </label>
            <%= f.fields_for :ext_links do |ext| %>
              <%= ext.select :ext_site, options_for_select(%w[Facebook Twitter Homepage Youtube Instagram]), {}, {:class => "form-control ext-link-select"} %>
              <%= ext.input :url, input_html: {:class => "ext-link-url"}, input_html: {:style => "display:inline;max-width:300px;", :placeholder => "URL"}, label: false %>
              <%= ext.link_to_remove "<i class=\"fa fa-minus-circle\"></i>".html_safe, class: "btn-ext-link-remove" %>
            <% end %>

            <%= f.link_to_add "Add Another Link", :ext_links, :id =>"btn-add-link", :class => "btn btn-primary" %>
            <br>
            <br>

            <%= f.fields_for :stages do |ff| %>
              <div class="textbox-wrap">
                
                <%= ff.input :capacity, input_html: {class:"form-control bfh-number", data_min: "0", value: "100"}, label: "Capacity (number of tickets available for each show)" %>
              </div>


              <div id="form-error-map" class="alert alert-warning" style="display:none;">
              </div>
              <%= ff.input :places_formatted_address_short, label:'Pin Your Venue\'s Location', :placeholder => "Enter a location", input_html: { :id => "pac-input", :class=>"controls"} %>
              <div id="map-canvas"></div>
              <div id="map-plz">
                Please make sure the appropriate location is pinned on the map above before continuing.
              </div>
              <%= ff.input :places_reference, as:"hidden" %>
            <% end %>

            <%= f.button :submit, :class => "btn btn-primary btn-create-board" %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</section>

app/views/boards/show.html.erb
<% if @board.header_image.exists? %>
  <section class="bg-parallax-dark" style="background-image: url(<%= @board.header_image.url %>);padding-bottom:50px;" data-stellar-background-ratio="0.5" data-stellar-vertical-offset="50">
<% else %>
  <section class="bg-parallax-dark" style="background-image: url(<%= asset_path "general/stockheader3.jpg" %>);padding-bottom:50px;" data-stellar-background-ratio="0.5" data-stellar-vertical-offset="50">
<% end %>
  <div class="container">
    <div class="padding-top hidden-xs"></div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center board-header" data-scrollreveal="enter left over 1s">
        <h1><%= @board.name %></h1>
        <p class="board-address">
          <%= link_to "#{@board.stages.first.place.formatted_address}".gsub(", United States", "").html_safe, "#map-canvas", :alt => "Map of venue location", :class =>"scrollto address-tooltip", :rel => "tooltip", "data-placement" => "bottom", :title => "Click to see map" %>
        </p>
        <p class="board-link-header text-enter">
          Links
        </p>
        <hr>
        
        <p class="ext-links-fontawesomed">
          <% if @board.ext_links.count > 0 %>
            <%= @board.ext_links_fontawesomed %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</section>

<section id="showboard" class="services-3 bg-lighter">
  <div class="container">
    <div class="row text-center">
      <div class="col-xs-6 col-xs-offset-3">
        <h2 id="showboard-title">Showboard</h2>
        <hr class="primary">
        <br>
      </div>
      <div class="col-xs-3">
        <% if user_signed_in? && current_user.boarder?(@board) && (current_user.board_role(@board) == "owner" || current_user.board_role(@board) == "manager") %>
          <% if !@board.header_image.exists? %>
            <%= link_to "Header Image", edit_board_path(@board), :class => "btn btn-primary btn-add-show" %>
            <%= link_to "Add Show", new_board_show_path(@board), :class => "btn btn-primary", :style => "float:right;" %>
          <% else %>
            <%= link_to "Add Show", new_board_show_path(@board), :class => "btn btn-primary btn-add-show" %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <% if @shows.count > 0 %>
          <%= render @shows %>
          <%= will_paginate @shows %>
        <% elsif user_signed_in? && current_user.boarder?(@board) && (current_user.board_role(@board) == "owner" || current_user.board_role(@board) == "manager") %>
          <p class="text-center">
            Your Showboard currently has no upcoming shows
          </p>          

        <% else %>
          <p class="text-center">
            This Showboard currently has no upcoming shows
          </p>    
        <% end %>
          
      </div>
    </div>
  </div>
</section>

<iframe
  id="map-canvas"
  width="100%"
  height="300"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB7grClbBKAv-FBjK8GWXXKjCI0-tHG63s
    &q=<%= @board.stages.first.place.name.gsub(" ","+").gsub("&", "") + @board.stages.first.place.formatted_address.gsub(" ", "+").gsub("$", "")  %>">
</iframe>