config/routes.rb
Showboarder::Application.routes.draw do
  devise_for :users, :path => '/users', :controllers => { :sessions => "users/sessions", :registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'static_pages#home'

  # devise_scope :user do
  #   match '/auth/stripe_connect/callback' => 'users/omniauth_callbacks#stripe_connect', :as => :auth_callback, via: [:get, :post]
  # end
  # devise_scope :user do
  #   get '/auth/stripe_connect/callback', to: 'users/omniauth_callbacks#stripe_connect'
  # end

  match '/about',   to: 'static_pages#about',   via: 'get'
  
  match '/status/:guid'      => 'sales#status',   via: :get,  as: :status
  match '/confirm/:guid'     => 'sales#show',     via: :get,  as: :confirm
  match '/esuggest/:act', to: 'acts#esuggest', via: 'get'
  match '/eretrieve/', to: 'acts#eretrieve', via: 'get'
  match '/ticketrelease/:ticket', to: 'tickets#release', via: :post
  match '/clearcart', to: 'tickets#clear', via: :post

  resources :users, only: [:show] do
    match '/stripe-connect' => 'users#stripe_connect', via: :get
  end

  resources :boards, only: [:create]

  resources :boards, except: [:index, :create], path:'' do
    match '/ticketed'    => 'boards#ticketed',      via: :get
    resources :shows do
      match '/checkin', to: 'shows#checkin', via: :get
      match '/checkinattendee', to: 'shows#checkin_attendee', via: :post
      match '/checkoutattendee', to: 'shows#checkout_attendee', via: :post
      match '/attendees', to: 'shows#attendees', via: :get
      match '/checkout', to: 'shows#checkout', via: :get
      match '/checkout', to: 'sales#checkout', via: :post
      match '/reserve', to: 'tickets#reserve', via: :post
    end
    resources :stages, only: [:create]
  end

  resources :acts, only: [:show]
  
  resources :stripe_events, only: [:create]
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :stage
  belongs_to :board
  has_many :ext_links, as: :linkable, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many :sales, as: :actionee, dependent: :destroy
  validates :ticketing_type, :price_door, :price_adv, presence: true
  has_and_belongs_to_many :acts
  accepts_nested_attributes_for :acts, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :ext_links, :reject_if => :all_blank, :allow_destroy => true
  delegate :vanity_url, :to => :board, :prefix => true
  before_save :normalize_category

  def destroy
    raise "Cannot delete a show with sold tickets. Email contact@showboarder.com if you need to do this" unless self.tickets_sold == 0
    # ... ok, go ahead and destroy
    super
  end

  def transact(actioner, state_before, state_after)
    Sale.create(actioner_id:actioner.id, actioner_type:actioner.class.to_s, actionee_id:self.id, actionee_type:"Show", state_before:state_before, state_after:state_after)
  end

  def acts_twitter_or_name
    combined = "" 
    self.acts.each do |act|
      combined += act.twitter_or_name
      if act != self.acts.last
        combined += ", "
      end
    end
    if combined.length > 2
      combined = "featuring " + combined
    end
    return combined
  end

  def normalize_category
    if self.category == "Business"
      self.category = "BusinessEvent"
      elsif self.category == "Comedy"
        self.category = "ComedyEvent"
      elsif self.category == "Dance"
        self.category = "DanceEvent"
      elsif self.category == "Food"
        self.category = "FoodEvent"
      elsif self.category == "Literary"
        self.category = "LiteraryEvent"
      elsif self.category == "Music"
        self.category = "MusicEvent"
      elsif self.category == "Sale"
        self.category = "SaleEvent"
      elsif self.category == "Social"
        self.category = "SocialEvent"
      elsif self.category == "Sports"
        self.category = "SportsEvent"
      elsif self.category == "Theater"
        self.category = "TheaterEvent"
    end
  end

  def denormalize_category
    if self.category == "BusinessEvent"
      return "Business"
      elsif self.category == "ComedyEvent"
        return "Comedy"
      elsif self.category == "DanceEvent"
        return "Dance"
      elsif self.category == "FoodEvent"
        return "Food"
      elsif self.category == "LiteraryEvent"
        return "Literary"
      elsif self.category == "MusicEvent"
        return "Music"
      elsif self.category == "SaleEvent"
        return "Sale"
      elsif self.category == "SocialEvent"
        return "Social"
      elsif self.category == "SportsEvent"
        return "Sports"
      elsif self.category == "TheaterEvent"
        return "Theater"
      else
        return category
    end
  end

  def tickets_make  # needs to account for paid, pwyw, rsvp_only
    if self.ticketing_type == "paid" || self.ticketing_type == "Ticketed"
      if self.custom_capacity?
        capacity = self.custom_capacity.to_i
      else
        capacity = self.board.stages.first.capacity.to_i
      end

      (1..capacity).each do |t|
        self.tickets.create(price:self.price_adv)
      end
    elsif self.ticketing_type == "rsvp"

    elsif self.ticketing_type == "pwyw"
    end #note that type of free just doesn't do anything
  end

  def unsold_count
    return self.tickets.where(state:"open").count
  end

  def tickets_price_update
    self.tickets.where(state:"open").each do |t|
      t.update(price:self.price_adv)
    end
  end

  def tickets_adjust(quantity)
    if self.tickets.count < quantity
      (self.tickets.count..quantity-1).each do |t|
        self.tickets.create
      end
    else
      if self.unsold_count > self.tickets.count - quantity
        self.tickets.each do |t|
          if t.bought_at == nil
            t.destroy
          end
          break if self.tickets.count == quantity
        end
      else
        flash[:error] = "Sorry, you cannot adjust capacity below the amount of tickets that have already sold."
        redirect_to board_show_path(@show.board, @show)
      end
    end
  end

  def tickets_reserve(quantity, reserver_id = nil, reserver_type = nil, reserve_code = nil)
    if self.unsold_count >= quantity
      #go through tickets of state that should be changed by state and change state buyer_id and buyer_type as appropriate via ticket state method 
      open = Ticket.where(show_id:self.id, state:"open")

      if reserve_code && quantity == 1 # TODO: catch if this is somehow ever hit with a quantity other than 1
        cart = Cart.find_by(reserve_code: reserve_code)
        added_ticket = open.first
        cart.tickets << added_ticket
        added_ticket.update_attributes(state:"reserved", ticket_owner_id:reserver_id, ticket_owner_type:reserver_type, reserved_at:DateTime.now)
      else

        cart = Cart.create(tickets:open[0..(quantity-1)])

        cart.tickets.each do |t|
          t.update_attributes(state:"reserved", ticket_owner_id:reserver_id, ticket_owner_type:reserver_type, reserved_at:DateTime.now)
          # t.buy_or_die
        end
      end

      if reserver_id == nil
        return cart.reserve_code
      end
    else
      raise "Sorry, not enough tickets are available at this time." # todo - say it's sold out instead of giving error page
    end
  end

  def tickets_buy(quantity, buyer_id, buyer_type)
    reserved = Ticket.where(show_id:self.id, state:"reserved", ticket_owner_id:buyer_id, ticket_owner_type:buyer_type)
    if reserved.length >= quantity
      (0..quantity-1).each do |t|
        reserved[t].update_attributes(state:"owned", bought_at:Time.now, buy_method:"online")
      end
    else
      raise "Sorry, not enough tickets are reserved by this user or guest."
      # redirect to show_path(@show)
    end
  end

  def tickets_clear_expired_reservations
    reserved = Ticket.where(show_id:self.id, state:"reserved")
    reserved.each do |t|
      if t.expired?
        t.make_open
      end
    end
  end

  def acts_stringed
    stringed = ""
    self.acts.each do |a|
      stringed = stringed + a.name
      if a != self.acts.last
        stringed = stringed + " - "
      end
    end
    return stringed
  end

  def attendees
    attendees = Hash.new { |hash, key| hash[key] = []}

    self.tickets.where('state=? OR state=?', 'owned', 'used').each do |t|
      attendees[t.ticket_owner.name] = attendees[t.ticket_owner.name] << t
    end
    return attendees
  end
  
  def checkin_attendee(id, type)
    tickets = self.tickets.where(ticket_owner_id: id, ticket_owner_type: type, state: "owned")

    tickets.each do |t|
      t.use
    end
  end

  def tickets_sold
    total_sold = 0
    self.tickets.each do |t|
      if t.state != "open"
        total_sold += 1
      end
    end
    return total_sold
  end

  def checkout_attendee(id, type)
    tickets = self.tickets.where(ticket_owner_id: id, ticket_owner_type: type, state: "used")

    tickets.each do |t|
      t.unuse
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  load_and_authorize_resource :board, :find_by => :vanity_url
  load_and_authorize_resource :show, :through => :board

  def new
    @board = Board.find_by_vanity_url(params[:board_id])
    @show = @board.shows.new
    @fb_link = @show.ext_links.build
    @fb_link.ext_site = "Facebook"
  end

  def checkout
    @reserve_code = ""
    @show = Show.find_by_id(params[:show_id])
    @show.tickets_clear_expired_reservations
    if user_signed_in?
      current_user.tickets_clear_expired_reservations
      @tickets = current_user.tickets.where(state:"reserved")
    else
      @reserve_code = ""
      @tickets = []
      if params[:reserve_code]
        @reserve_code = params[:reserve_code]

        cart = Cart.find_by_reserve_code(@reserve_code)

        carted = cart.tickets

        carted.each do |t| # TODO: DRY this
          if t && !t.expired?
            @tickets << t
          elsif t
            t.make_open("Reservation expired before state change")
          else
            next
          end
        end
      end
      
    end
    @amount = 0

    @tickets.each do |t|
      @amount = @amount + t.price
    end

    if @tickets.count == 0
      redirect_to board_show_path(@show.board, @show)
    end

    @sale = Sale.new
  end

  def create
    @board = Board.find_by_vanity_url(params[:board_id])
    @show = @board.shows.new(show_params)
    @show.show_at = ApplicationController.helpers.date_plus_time(params[:show_date], params[:show_time], @board.timezone)
    @show.door_at = ApplicationController.helpers.date_plus_time(params[:show_date], params[:door_time], @board.timezone)
    @show.stage = @board.stages.first

    if @show.ticketing_type == "Sell tickets to the show"
      @show.ticketing_type = "paid"
    else
      @show.ticketing_type = "free"
    end

    if @show.save
      @show.update_attributes(state:"public") # TODO - allow for the creation of pending shows
      @show.acts.each do |e| # loop through all shows acts and merge duplicated acts.
        if e.echonest_id[0..4] == "ECHO-" #this is a check for if the DB query in esuggest was too dumb to find the act in the DB
          temp_echo = e.echonest_id.gsub("ECHO-", "")
          if Act.find_by(echonest_id: temp_echo)
            # TODO: refactor this whole action and mostly make it use the logic in this if case
            e.echonest_id = temp_echo
          end
        end
        if e.echonest_id
          if e.echonest_id[0..2] == "DB-" # found in DB, has no echonest ID = id is "DB-act_id
            dupe = Act.find_by(id: e.echonest_id.gsub("DB-", "").to_i)

            dupe.shows << @show

            e.ext_links.each do |l| # update already-saved act with new act links
              link_uora = dupe.ext_links.find_or_create_by(ext_site:l.ext_site) # uora = updated or added
              link_uora.url = l.url

              link_uora.save!
            end

            e.destroy! # destroy link now that links and show have been merged with existing record
          elsif e.echonest_id[0..4] == "ECHO-" # not found in DB, so ID = "ECHO-echonest_id"
            e.echonest_id = e.echonest_id.gsub("ECHO-", "")
            e.save!
          else # found in db, has echonest ID so id is echonest id
            dupe = Act.find_by(echonest_id: e.echonest_id)

            dupe.shows << @show

            e.ext_links.each do |l| # update already-saved act with new act links
              link_uora = dupe.ext_links.find_or_create_by(ext_site:l.ext_site) # uora = updated or added
              link_uora.url = l.url

              link_uora.save!
            end

            dupe.save!

            e.destroy!
          end
        end
      end
      if @show.ticketing_type == "paid"
        @show.tickets_make
      end
      flash[:success] = "You have added a show!"
      redirect_to [@board, @show]
    else
      render 'new'
    end
  end

  def checkin
    @show = Show.find(params[:show_id])
  end

  def checkin_attendee
    @show = Show.find(params[:show_id])
    @attendee = params[:attendee]

    if @show.checkin_attendee(@attendee["attendee_id"], @attendee["attendee_type"])
      render :json => { status: :checked_in }
    else
      render :json => { status: :unprocessable_entity }
    end
  end

  def checkout_attendee
    @show = Show.find(params[:show_id])
    @attendee = params[:attendee]

    if @show.checkout_attendee(@attendee["attendee_id"], @attendee["attendee_type"])
      render :json => { status: :checkedOut }
    else
      format.json { render json: {attendee: @attendee["attendee_id"]}, status: :unprocessable_entity }
    end
  end

  def attendees
    @show = Show.find(params[:show_id])

    attendees = @show.attendees.sort_by do |name|
      name.split(" ").last
    end

    respond_to do |format|
      format.json   { render :json => attendees.to_json }
    end
  end

  def show
    @show = Show.find(params[:id])
    @board = @show.board
    @acts_stringed = @show.acts_stringed
  end

  def update
    @show = Show.find(params[:id])

    @show.show_at = ApplicationController.helpers.date_plus_time(params[:show_date], params[:show_time], @board.timezone)
    @show.door_at = ApplicationController.helpers.date_plus_time(params[:show_date], params[:door_time], @board.timezone)
    if @show.update(show_params) # TODO - allow for editing of google place
      @show.tickets_price_update
      flash[:success] = "Show updated"
      redirect_to board_show_path(@board, @show)
    else
      render 'edit'
    end
  end

  def edit
    @show = Show.find(params[:id])
    @board = @show.board

    if @show.ext_links.count == 0
      @fb_link = @show.ext_links.build
    end
  end

  def destroy
    @show = Show.find(params[:id])
    @board = @show.board
    if @show.tickets_sold != 0
      flash[:error] = "Deletion prevented.  Tickets have already been sold. Email contact@showboarder.com if you need to do this"
      redirect_to @board
    elsif current_user.boarder?(@board)
      board_role = current_user.board_role(@board)
      if board_role == "owner" || board_role == "manager"
        @show.destroy
      end
      flash[:success] = "Show deleted"
      redirect_to @board
    end
  end

  private

    def show_params
      params.require(:show).permit(:state, :error, :announce_at, :door_at, :min_age, :ticketing_type, :category, :show_at, :custom_capacity, :payer_id, :title, :paid_at, :price_adv, :price_door, :board, {ext_links_attributes: [:id, :ext_site, :url, :linkable_type, :_destroy]}, {acts_attributes: [{ext_links_attributes: [:id, :ext_site, :url, :linkable_type, :_destroy]},:id, :name, :email, :echonest_id, :_destroy ]})
    end
end

app/views/shows/_reserve_tickets_button.html.erb
<%= form_tag board_show_reserve_path(@board, @show) do %>

  <label class="amount">
    <span>Ticket quantity</span>
  </label>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3 ticket-reserve-wrapper">
      <%= number_field_tag 'quantity', params[:quantity], :class => "form-control ticket-reserve bfh-number", value: 1, :in => 1...8, required: "required", name: "quantity", wrapper_class: "input-group-ticket-quantity" %> 
    </div>
    <div class="col-xs-6 col-xs-offset-3">
      <%= submit_tag "Proceed to Checkout", class: "btn btn-primary btn-reserve" %>
    </div>
  </div>
<% end %>

app/views/shows/_show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="row">
      <div class="col-xs-3 col-md-2 vcenter">
        <h4 class="show-meta">
          <%= show.show_at.to_time.strftime('%b %e') %>
        </h4>
        <% if show.ticketing_type == "paid" %>
          <h4 class="show-meta">
            <%= number_to_currency(show.price_adv, unit:"$", :precision => 0) %>
          </h4>
        <% else %>
          <h4 class="show-meta">
            FREE
          </h4>
        <% end %>
        <% if show.show_at %>
          <h4 class="show-meta">
            <%= show.show_at.to_time.strftime('%l:%M %p') %>
          </h4>
        <% end %>
        <% if show.min_age %>
          <h4 class="show-meta">
            <%= show.min_age %>
          </h4>
        <% end %>
      </div><!--
    --><div class="col-sm-6 col-xs-5 col-md-8 text-center vcenter">
        <% if show.title %>
          <h3 class="show-title">
            <%= show.title.upcase %>
          </h3>          
        <% end %>
        <h3 class="show-acts">
          <% show.acts.each do |a| %>
            <%= link_to a.name.to_s, a %>
            <% if a != show.acts.last %>
              -
            <% end %>          
          <% end %>
        </h3>
      </div><!--
    --><div class="col-sm-3 col-xs-4 col-md-2 vcenter text-right">
          <% if show.ticketing_type == "paid" %>
            <%= link_to "Buy Tickets #{number_to_currency(show.price_adv, unit:"$", :precision => 0)}", board_show_path(@board, show), class: "btn btn-default btn-show" %><!--
      --><br>
          <% else %>
            <%= link_to "Event Details", board_show_path(@board, show), class: "btn btn-default btn-show" %><!--
        --><br>
          <% end %>
        <% if user_signed_in? && current_user.boarder?(show.board) && current_user.board_role(show.board) == "owner" %>
          <%= link_to "Delete show", [@board, show], method: :delete, id: show.id,
                                           data: { confirm: "Are you sure you would like to delete this show?  This cannot be undone." },
                                           title: show.id %>
          <br>
          <%= link_to "Edit show", edit_board_show_path(@board, show) %>
          <br>
          <%= link_to "Show Checkin", board_show_checkin_path(@board, show) %>
        <% end %>
      </div>
    </div>
    <hr>
  </div>
</div>

app/views/shows/checkin.html.erb
<div class="container no-section">
  <div class="row">
    <div class="col-xs-12 text-center">
      <%= react_component('CheckInList', {name: 'react-test', 
                    source: "/#{@show.board.vanity_url}/shows/#{@show.id}/attendees", checkInRoute: "/#{@show.board.vanity_url}/shows/#{@show.id}/checkinattendee", checkOutRoute: "/#{@show.board.vanity_url}/shows/#{@show.id}/checkoutattendee"}, {prerender: true}) %>
    </div>
  </div>
</div>

app/views/shows/checkout.html.erb
<!-- <%= javascript_include_tag :eForm %> -->
<section>
  <div class="container eternity-form">
    <div class="registration-form-section">

      <% if user_signed_in? %>
        <%= render 'shows/purchase_tickets_logged_in', :sale => @sale %>
      <% else %>
        <%= render 'shows/purchase_tickets_logged_out', :sale => @sale %>
      <% end %>
      <br>
    </div>
    <div class="col-sm-6 registration-right-section">
      <div class="reg-content right-section-content">
        <div class="textbox-wrap tickets-section">
          <div class="section-title tickets-section-title text-center">
            <h3>Cart</h3>
          </div>
          <h4 class="text-center">
            <% if @tickets.count == 1 %>
              <%= "1 Ticket" %>
            <% else %>
              <%= @tickets.count %> Tickets
            <% end %>
          </h4>
          <hr>
          <div class="row">
            <div class="col-xs-6">
              Remove
            </div>

            <div class="col-xs-6">
              <span class="pull-right">Duplicate</span>
            </div>
          </div>

          <% @tickets.each do |t| %>
            <script>
              $(function () {
                var expiration = new Date();
                expiration = new Date(<%= (t.reserved_at + 15.minutes).to_i * 1000 %>);
                $('#defaultCountdown<%= t.id %>').countdown({until: expiration, format:'MS', compact:'true'});
              });
            </script>
            
            <div class="row ticket text-center">
              <div class="col-xs-2">
                <% if user_signed_in? %>
                  <%= link_to "<i class=\"fa fa-minus-circle btn-ticket-remove\"></i>".html_safe, "/ticketrelease/" + t.guid, method: :post, remote: true %>
                <% else %>
                  <%= link_to "<i class=\"fa fa-minus-circle btn-ticket-remove\"></i>".html_safe, "/ticketrelease/" + t.guid + "?reserve_code=" + @reserve_code, method: :post, remote: true %>
                <% end %>
              </div>
              <div class="col-xs-3 text-center">
                <div id="defaultCountdown<%= t.id %>"></div>
              </div>
              <div class="col-xs-4">
                <%= link_to t.show.show_at.to_time.strftime('%b %e'), board_show_path(t.show.board, t.show), target: "_blank" %>
              </div>
              <div class="col-xs-3">
                <% if user_signed_in? %>
                  <%= link_to "<i class=\"fa fa-plus-circle btn-ticket-add\"></i>".html_safe, board_show_reserve_path(t.show.board, t.show, :quantity => "1"), method: :post, remote: true %>
                <% else %>
                  <%= link_to "<i class=\"fa fa-plus-circle btn-ticket-add\"></i>".html_safe, board_show_reserve_path(t.show.board, t.show, :quantity => "1", reserve_code: @reserve_code), method: :post, remote: true %>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-xs-12">
              <% if user_signed_in? %>
                <%= link_to "Clear cart", clearcart_path, class: "pull-right", method: :post, remote: true %>
              <% else %>
                <%= link_to "Clear cart", clearcart_path(reserve_code:@reserve_code), class: "pull-right", method: :post, remote: true %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shows/show.html.erb
<section id="show">
<div class="container">
<div class="row">
  <div class="col-xs-12 text-center">
    <% if @show.title %>
      <h1>
        <%= @show.title.upcase %>
      </h1>
    <% end %>
    <br>
    <% if @show.title %>
      <h2>
        <%= @show.show_at.to_time.strftime('%B %e') %> at <%= link_to "#{@show.board.name}", @show.board %></h1>
      </h2>
    <% else %>
      <h1>
        <%= @show.show_at.to_time.strftime('%B %e') %> at <%= link_to "#{@show.board.name}", @show.board %></h1>
      </h1>
    <% end %>
    <br>
    <% if @show.acts.count > 0 %>
      <h2>
        <% @show.acts.each do |a| %>
          <%= link_to a.name.to_s, a %>
          <% if a != @show.acts.last %>
            -
          <% end %>          
        <% end %>
      </h2>
    <% end %>
    <br>
      
    <h3>
      Doors <%= @show.door_at.to_time.in_time_zone(@show.board.timezone).strftime('%l:%M %p') %> - Show <%= @show.show_at.to_time.in_time_zone(@show.board.timezone).strftime('%l:%M %p') %>
    </h3>

    <h3>
      <% if @show.price_adv != @show.price_door %>
        <%= number_to_currency(@show.price_adv, unit:"$", :precision => 0) %> advance - <%= number_to_currency(@show.price_door, unit:"$", :precision => 0) %> at the door
      <% elsif  @show.price_adv.to_i == 0 && @show.price_door.to_i == 0  %>

      <% else %>
        <%= number_to_currency(@show.price_adv, unit:"$", :precision => 0) %> advance or at the door
      <% end %>

    </h3>
    <br>

    <h3>
      <% if @show.ext_links.count == 1 %>
        <%= link_to "<i class=\"fa fa-facebook-square\"></i>".html_safe + "  Facebook Event Page", @show.ext_links.first.url, target: "_blank" %>
      <% end %>
    </h3>

    <% if @show.ticketing_type == "Ticketed" || @show.ticketing_type == "paid" %>
      <%= render 'reserve_tickets_button' %>
    <% else %>
      <h3>This show is free!</h3>
    <% end %>


    <div class="row text-center">
      <div class="col-xs-12" style="margin-top:40px;margin-bottom:10px;">
        Excited? Share this show!
      </div>
      <br>
    </div>
    <div class="row" >
      <div class="col-xs-6 text-right">
        <a href="https://twitter.com/share" class="twitter-share-button" data-text="Excited for this show at <%= @show.board.twitter_or_name %> <%= @show.acts_twitter_or_name %>" data-via="showboarder">Tweet</a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
      </div>
      <div class="col-xs-6 text-left">

        <div class="fb-share-button" style="padding-left:50px;" data-href="https://www.showboarder.com/<%= @board.vanity_url %>/shows/<%= @show.id %>" data-layout="button"></div>

        <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=1431631563750055&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
      </div>
    </div>

    <% if user_signed_in? && current_user.boarder?(@show.board) && (current_user.board_role(@show.board) == "owner" || current_user.board_role(@board) == "manager") %>
      <p>
        <%= link_to "Edit show", edit_board_show_path(@board, @show) %>
      </p>
    <% end %>
  </div>
  </div>
</div>
</section>
<script>
  $(function() {
    var reservePriceUpdate = function() {
      var reservePrice = 0
      var btnString = ""

      reservePrice = parseInt($('.ticket-reserve').val() * <%= @show.price_adv %>)

      btnString = "$" + reservePrice.toString() + " Proceed to Checkout"
      $('.btn-reserve').val(btnString)
    }
    reservePriceUpdate();

    $('.ticket-reserve').change(function() {
      reservePriceUpdate();
    })
  });
</script>